services:

  postgres:
    image: postgres:17
    container_name: ai-sql-postgres

    env_file:
      - ./ai-sql-generator/.env

    environment:
      POSTGRES_DB: ai_sql_generator
      POSTGRES_USER: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_sql_generator"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./ai-sql-generator
      dockerfile: Dockerfile

    container_name: ai-sql-backend

    env_file:
      - ./ai-sql-generator/.env

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ai_sql_generator
      DB_USERNAME: postgres

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: ai-sql-frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend


volumes:
  postgres-data: