"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "../../src/lib/api";

export default function HistoryPage() {

  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("token");

    if (!token) {
      router.push("/login");
    }
  }, [router]);

  const [history, setHistory] = useState([]);

  const [loading, setLoading] = useState(true);

  const [error, setError] = useState("");

  const [deletingId, setDeletingId] = useState(null);


  // ============================================================
  // LOAD HISTORY
  // ============================================================

  useEffect(() => {

    async function loadHistory() {

      try {

        const data = await apiRequest(
          "/api/query/history"
        );

        setHistory(data);

      } catch (error) {

        setError(error.message);

      } finally {

        setLoading(false);

      }

    }

    loadHistory();

  }, []);


  // ============================================================
  // DELETE QUERY
  // ============================================================

  async function deleteQuery(id) {

    const confirmed = window.confirm(
      "Are you sure you want to delete this query?"
    );

    if (!confirmed) {
      return;
    }

    setDeletingId(id);

    setError("");

    try {

      await apiRequest(
        `/api/query/history/${id}`,
        {
          method: "DELETE"
        }
      );

      // Remove the deleted query immediately
      // without refreshing the page.
      setHistory((currentHistory) =>
        currentHistory.filter(
          (item) => item.id !== id
        )
      );

    } catch (error) {

      setError(error.message);

    } finally {

      setDeletingId(null);

    }
  }


  return (
    <main className="app-shell min-h-screen">

      {/* Navigation */}

      <nav className="glass-nav">

        <div className="page-content max-w-6xl mx-auto px-5 sm:px-8 py-4 flex items-center justify-between">

          <button
            onClick={() => router.push("/dashboard")}
            className="flex items-center gap-3"
          >

            <span className="h-9 w-9 rounded-xl bg-white text-black flex items-center justify-center font-black text-sm">
              SQL
            </span>

            <div>

              <h1 className="font-bold">
                Query History
              </h1>

              <p className="text-[11px] text-zinc-500">
                Your generated queries
              </p>

            </div>

          </button>

          <button
            onClick={() => router.push("/query")}
            className="primary-btn rounded-lg px-4 py-2 text-sm"
          >
            + New Query
          </button>

        </div>

      </nav>


      {/* Main */}

      <div className="page-content max-w-6xl mx-auto px-5 sm:px-8 py-12">

        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-8">

          <div>

            <p className="text-xs uppercase tracking-[.25em] text-zinc-500 mb-3">
              Activity
            </p>

            <h2 className="text-3xl sm:text-4xl font-semibold tracking-tight">
              Recent queries
            </h2>

            <p className="text-zinc-500 mt-2">
              Review the questions and SQL generated by the assistant.
            </p>

          </div>

          <div className="text-sm text-zinc-500">
            {history.length}{" "}
            {history.length === 1 ? "query" : "queries"}
          </div>

        </div>


        {/* Loading */}

        {loading && (

          <div className="glass-card rounded-2xl p-8 text-center text-zinc-400">
            Loading history...
          </div>

        )}


        {/* Error */}

        {error && (

          <div className="status-error rounded-2xl p-5 mb-5">
            {error}
          </div>

        )}


        {/* Empty */}

        {!loading && history.length === 0 && (

          <div className="glass-card rounded-3xl p-12 text-center">

            <div className="mx-auto h-14 w-14 rounded-2xl border border-white/10 bg-white/5 flex items-center justify-center text-xl">
              ⌘
            </div>

            <h3 className="font-semibold text-xl mt-5">
              No queries yet
            </h3>

            <p className="text-zinc-500 mt-2">
              Your generated SQL will appear here.
            </p>

            <button
              onClick={() => router.push("/query")}
              className="primary-btn rounded-lg px-5 py-3 mt-6 text-sm"
            >
              Generate your first query
            </button>

          </div>

        )}


        {/* History list */}

        <div className="space-y-5">

          {history.map((item) => (

            <div
              key={item.id}
              className="glass-card glass-card-hover rounded-2xl p-5 sm:p-6"
            >

              <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">

                <div className="min-w-0">

                  <p className="text-xs text-zinc-500 uppercase tracking-wider mb-2">
                    Natural language
                  </p>

                  <h3 className="font-semibold text-lg text-zinc-100 break-words">
                    {item.naturalLanguageQuery}
                  </h3>

                </div>


                {/* Right side */}

                <div className="flex items-center gap-3 shrink-0">

                  <span
                    className={`text-xs font-semibold px-3 py-1.5 rounded-full border ${
                      item.executionStatus === "SUCCESS"
                        ? "border-white/20 bg-white/10 text-white"
                        : "border-white/15 bg-black/20 text-zinc-400"
                    }`}
                  >
                    {item.executionStatus}
                  </span>


                  {/* Delete button */}

                  <button
                    onClick={() => deleteQuery(item.id)}
                    disabled={deletingId === item.id}
                    title="Delete query"
                    className="h-9 w-9 rounded-lg border border-white/10 bg-white/5 text-zinc-400 hover:text-white hover:bg-white/10 hover:border-white/20 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
                  >

                    {deletingId === item.id ? (
                      <span className="text-xs">
                        ...
                      </span>
                    ) : (
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M3 6h18" />
                        <path d="M8 6V4h8v2" />
                        <path d="M19 6v14H5V6" />
                        <path d="M10 11v5" />
                        <path d="M14 11v5" />
                      </svg>
                    )}

                  </button>

                </div>

              </div>


              {/* SQL */}

              <pre className="code-panel mt-5 p-5 rounded-xl overflow-x-auto text-sm leading-6 font-mono whitespace-pre-wrap">
                {item.generatedSql}
              </pre>


              {/* Date */}

              <p className="text-zinc-600 text-xs mt-4">
                {item.createdAt}
              </p>

            </div>

          ))}

        </div>

      </div>

    </main>
  );
}