package com.example.aisqlgenerator.service;

import com.example.aisqlgenerator.exception.ValidationException;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;

import org.springframework.stereotype.Service;

@Service
public class ValidationService {

    public void validate(String sql) {

        // 1. Check if SQL is empty
        if (sql == null || sql.isBlank()) {

            throw new ValidationException(
                    "AI returned empty SQL"
            );
        }

        // 2. Validate SQL syntax
        try {

            Statement statement =
                    CCJSqlParserUtil.parse(sql);

            if (statement == null) {

                throw new ValidationException(
                        "Invalid SQL generated by AI"
                );
            }

        } catch (JSQLParserException e) {

            throw new ValidationException(
                    "Invalid SQL generated by AI"
            );
        }
    }
}